"""Generate docs/DEID_METHOD.md from the identifier table and the measured run.

The Safe Harbor table is rendered from `phi.SAFE_HARBOR` and the performance
numbers from `out/results.json`, so the document cannot drift from the code or
claim a recall the pipeline did not achieve.

Run:  python write_method.py     (after run_pipeline.py)
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))
import phi

DOC = "docs/DEID_METHOD.md"


def main():
    os.makedirs("docs", exist_ok=True)
    res = json.load(open("out/results.json"))
    d = res["deid"]

    L = ["# De-identification method", "",
         "Generated by `write_method.py` from `src/phi.py` and the measured run",
         "in `out/results.json`. The table cannot drift from the code and the",
         "numbers cannot drift from the run.", "",
         "## What this approximates, and what it does not certify", "",
         "This pipeline approximates the **Safe Harbor** method, 45 CFR",
         "164.514(b)(2): remove the 18 enumerated identifiers, and have no",
         "actual knowledge that the residual information could identify an",
         "individual.",
         "",
         "It is **not** Expert Determination, 164.514(b)(1). That route requires",
         "a person with appropriate statistical training to determine that the",
         "re-identification risk is very small **given the specific data, the",
         "specific recipients, and the controls in place**, to document the",
         "method and the analysis, and to state a period after which it must be",
         "re-assessed. Nothing here is a determination and no one here is",
         "qualified to make one.",
         "",
         "The distinction is not pedantry, because the two routes answer",
         "different needs. Safe Harbor is a checklist and is cheap. Expert",
         "Determination is what an organisation needs when it must **retain**",
         "something Safe Harbor strips -- full dates for a longitudinal study,",
         "5-digit ZIPs for a geographic access analysis, ages above 89 for a",
         "frailty cohort. If a research team asks for any of those, the answer",
         "is not 'we can loosen the pipeline', it is 'that needs a",
         "determination'.",
         "",
         "**Neither route makes the data anonymous.** Safe Harbor output is",
         "de-identified under HIPAA, which is a legal status, not a mathematical",
         "guarantee. It carries no formal privacy bound; differential privacy",
         "is the tool that does, and it is not used here.",
         "",
         "## The 18 identifiers", "",
         "Every identifier is listed, including those absent from this data.",
         "The complete table is the deliverable: a method document listing only",
         "the identifiers that happened to be present tells a reviewer nothing",
         "about the ones that were never considered.", "",
         "| # | identifier | in data | detection | transformation | residual risk |",
         "|---|---|---|---|---|---|"]
    for n, name, present, det, trans, residual in phi.SAFE_HARBOR:
        mark = "yes" if present else "**no**"
        L.append(f"| {n} | {name} | {mark} | {det} | {trans} | {residual} |")

    L += ["", "## Measured performance against planted ground truth", "",
          "Synthetic claims contain no PHI, so PHI was deliberately planted back",
          "into free text with its exact character offsets logged",
          "(`src/phi.py`). Those offsets are the ground truth below. This is what",
          "turns 'the data was anonymised' from a sentence into an engineering",
          "result.", "",
          "| identifier | planted | found | missed | recall | over-redactions |",
          "|---|---|---|---|---|---|"]
    for k in sorted(d, key=lambda x: -d[x]["n_truth"]):
        b = d[k]
        if not b["n_truth"]:
            continue
        rec = f"{b['recall']:.1%}" if b["recall"] is not None else "n/a"
        L.append(f"| {k} | {b['n_truth']:,} | {b['tp']:,} | {b['fn']:,} | "
                 f"**{rec}** | {b['fp']:,} |")
    L += [f"| **overall** | | | | **{res['deid_overall_recall']:.1%}** | |", "",
          "### Why recall and precision are never averaged", "",
          "A **miss is a disclosure**: PHI that survived into a dataset everyone",
          "downstream believes is de-identified, and it will be handled",
          "accordingly -- copied, joined, emailed. A **false positive is",
          "over-redaction**: it costs analytic utility, which is a real cost and",
          "a recoverable one, because the original is still there to re-run.",
          "",
          "These are not commensurable, so there is no F1 in this document.",
          "",
          "### Why names are not at 99%", ""]
    name = d.get("name", {})
    if name:
        L += [f"Name recall is **{name['recall']:.1%}**, below the >99% a payer",
              "would want. That is by construction and it is the honest number:",
              "**30% of members carry surnames deliberately absent from the",
              "detector's gazetteer**, so those names are recoverable only from",
              "context (`Patient X`, `Dr. X`, `spoke with X`).",
              "",
              "A name detector evaluated against the same list it was built from",
              "reports 100% and measures nothing but its own internal",
              "consistency. The split pools exist so this number is real.",
              "",
              f"There are also **{name['fp']:,} over-redactions**, and their cause",
              "is worth naming: facility names that collide with surnames --",
              "`Parker Regional`, `Baker Memorial`, `Mason General`. No",
              "gazetteer distinguishes `Mr Parker` from `Parker Regional`",
              "without more context, and over-redacting the facility name",
              "destroys the site variable that every provider-level analysis",
              "needs. This is the actual daily trade-off in de-identification",
              "work, not a rounding error.",
              "",
              "Reaching >99% needs a different architecture: a trained NER model",
              "rather than a gazetteer, plus human review of flagged documents.",
              "Tuning the split until the number looked better would have been",
              "the dishonest option available here.", ""]

    L += ["## Design decisions worth defending", "",
          "### Dates are shifted, not deleted", "",
          "Each patient gets a deterministic offset and every date for that",
          "patient moves by it. Within-patient intervals are preserved exactly.",
          "",
          "Deleting dates satisfies Safe Harbor and silently corrupts:",
          "readmission windows, length of stay, medication adherence and gap",
          "measures, episode construction, pre/post comparisons, and any",
          "survival analysis. Those are most of what claims data is for.",
          "",
          "The cost: shifting is weaker than deletion. An attacker who learns one",
          "true date for one patient recovers that patient's offset and hence",
          "all of their dates. Offsets are per-patient rather than global, so",
          "the compromise does not propagate beyond the one person.",
          "",
          "### ZIP is truncated to 3 digits, and sometimes to 000", "",
          "Safe Harbor permits the first three digits **unless** the 3-digit",
          "area contains 20,000 people or fewer, in which case it must be 000.",
          "That rule is implemented, and the population table is illustrative",
          "rather than the Census Bureau's file -- a real deployment loads the",
          "current file and re-checks it when the Bureau republishes, because",
          "the list of restricted ZIP3s changes.",
          "",
          "### Provider NPI is retained, deliberately", "",
          "NPI identifies the provider, not the patient, and is not patient PHI",
          "under Safe Harbor. It is retained because provider-level analytics",
          "need it. It is nonetheless a re-identification vector when combined",
          "with a date and a small geography, and that is a documented decision",
          "rather than an oversight -- which is the difference between a risk",
          "you accepted and a risk you missed.",
          "",
          "### Identifier #18 cannot be automated", "",
          "'Any other unique identifying number, characteristic, or code' is",
          "where Safe Harbor pipelines actually fail. A rare diagnosis plus a",
          "3-digit ZIP can identify someone with all seventeen other identifiers",
          "removed, and no regex catches it. This pipeline flags free-text",
          "employer and occupation mentions for review and does nothing else,",
          "which is a gap, not a solution.",
          "",
          "## De-identification is one layer, not the answer", "",
          "The recall table above measures one control. A de-identified dataset",
          "with no access controls, no minimum-necessary review, and no audit",
          "trail is not safe, and a missed name in a system that has all three",
          "is contained in a way it is not in a system that has only",
          "de-identification.",
          "",
          "What a real deployment needs alongside this: minimum-necessary review",
          "of the released columns, role-based access with logging, a data-use",
          "agreement binding the recipient not to attempt re-identification, and",
          "a re-identification risk review when the released data changes shape.",
          ""]

    with open(DOC, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"wrote {DOC} ({len(L)} lines)")


if __name__ == "__main__":
    main()
